### DISCUSSION TITLE
GitHub Actions

### DISCUSSION THREAD

**Discussion by mportesdev** [underground-lab/eu2020#23] [Ideas]
nápad: testy v `test.yml` nechat běžet na více verzích Pythonu pomocí

```yaml
strategy:
  matrix:
    python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
```
